// SPDX-License-Identifier: MIT OR Apache-2.0
//! fclone's capture pipeline against faicey + ollywoo under node (testing/fclone/make_pose_oracle.mjs): Math.atan2
//! (324 specials bit for bit, 200,000 generated by digest), frontality (50,000 matrices), poseNormalize, aggregate
//! and fclone(frames) → faceprint on 60 generated frame sets. Inputs are regenerated here from the same exact LCG.
use streamair::fclone::{self, Frame, Point};
use voaice::json::{self, Value};
use voaice::sha256;

const M31: u64 = 2147483647;
struct Lcg(u64);
impl Lcg {
    fn new(seed: u64) -> Self {
        let s = seed % M31;
        Lcg(if s == 0 { 1 } else { s })
    }
    fn next(&mut self) -> f64 {
        self.0 = self.0 * 16807 % M31;
        self.0 as f64 / M31 as f64
    }
}
fn digest(v: &[f64]) -> String {
    let mut b = Vec::with_capacity(v.len() * 8);
    for x in v {
        b.extend_from_slice(&x.to_le_bytes());
    }
    sha256::hex(&sha256::digest(&b))
}
fn bits(x: f64) -> String {
    sha256::hex(&x.to_le_bytes())
}
fn from_bits(h: &str) -> f64 {
    let mut b = [0u8; 8];
    for i in 0..8 {
        b[i] = u8::from_str_radix(&h[2 * i..2 * i + 2], 16).unwrap();
    }
    f64::from_le_bytes(b)
}
fn oracle() -> Value {
    json::parse(&std::fs::read_to_string("tests/fixtures/pose_oracle.json").unwrap()).unwrap()
}
fn val(r: &mut Lcg) -> f64 {
    let m = r.next();
    let e = (r.next() * 80.0).floor() - 40.0;
    let sgn = if r.next() < 0.5 { -1.0 } else { 1.0 };
    sgn * m * 2f64.powi(e as i32)
}
fn mat(r: &mut Lcg) -> Vec<f64> {
    (0..16).map(|_| r.next() * 3.0 - 1.5).collect()
}

#[test]
fn atan2_is_v8s_bit_for_bit() {
    let o = oracle();
    let a = o.get("atan2").unwrap();
    let Value::Arr(specials) = a.get("specials").unwrap() else { panic!() };
    for c in specials {
        let Value::Arr(t) = c else { panic!() };
        let (y, x, want) = (from_bits(t[0].as_str().unwrap()), from_bits(t[1].as_str().unwrap()), t[2].as_str().unwrap());
        let got = fclone::js_atan2(y, x);
        assert!(bits(got) == want || (got.is_nan() && from_bits(want).is_nan()), "atan2({y:e}, {x:e}) = {got:e}");
    }
    let mut r = Lcg::new(1);
    let out: Vec<f64> = (0..200000).map(|_| { let y = val(&mut r); let x = val(&mut r); fclone::js_atan2(y, x) }).collect();
    assert_eq!(digest(&out), a.get("digest").unwrap().as_str().unwrap(), "200,000 generated atan2");
}

#[test]
fn libm_atan2_is_not_v8s() {
    // the discriminator: Rust's f64::atan2 (the system libm) on the same 200,000 pairs
    let mut r = Lcg::new(1);
    let mut differ = 0;
    for _ in 0..200000 {
        let y = val(&mut r);
        let x = val(&mut r);
        if y.atan2(x).to_bits() != fclone::js_atan2(y, x).to_bits() {
            differ += 1;
        }
    }
    eprintln!("the system libm's atan2 differs from V8's on {differ} of 200,000 pairs");
    assert!(differ > 0, "if libm agreed everywhere, the 200,000 pairs would not be evidence for the fdlibm port");
}

#[test]
fn frontality_matches() {
    let o = oracle();
    let mut r = Lcg::new(2);
    let out: Vec<f64> = (0..50000).map(|_| fclone::frontality(Some(&mat(&mut r)))).collect();
    assert_eq!(digest(&out), o.path(&["frontality", "digest"]).unwrap().as_str().unwrap());
}

fn frames(seed: u64, n: usize, kind: &str) -> Vec<Frame> {
    let mut r = Lcg::new(seed);
    let base: Vec<Point> = (0..468).map(|_| Point { x: r.next(), y: r.next(), z: (r.next() - 0.5) * 0.2 }).collect();
    (0..n)
        .map(|_| {
            let landmarks = base.iter().map(|p| Point {
                x: p.x + (r.next() - 0.5) * 1e-3, y: p.y + (r.next() - 0.5) * 1e-3, z: p.z + (r.next() - 0.5) * 1e-3,
            }).collect();
            let matrix = match kind {
                "none" => None,
                "identity" => Some(vec![1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.]),
                _ => Some(mat(&mut r)),
            };
            Frame { landmarks, matrix }
        })
        .collect()
}
fn flat(p: &[Point]) -> Vec<f64> {
    p.iter().flat_map(|q| [q.x, q.y, q.z]).collect()
}

#[test]
fn pose_normalize_aggregate_and_the_capture_pipeline_match() {
    let o = oracle();
    let Value::Arr(cases) = o.get("cases").unwrap() else { panic!() };
    let mut printed = 0;
    for c in cases {
        let seed = c.get("seed").unwrap().as_f64().unwrap() as u64;
        let n = c.get("n").unwrap().as_f64().unwrap() as usize;
        let kind = c.get("kind").unwrap().as_str().unwrap();
        let fr = frames(seed, n, kind);
        let norm = fclone::pose_normalize(&fr[0].landmarks, fr[0].matrix.as_deref());
        assert_eq!(digest(&flat(&norm)), c.get("poseNormalize").unwrap().as_str().unwrap(), "poseNormalize, seed {seed}");
        let agg = fclone::aggregate(&fr).unwrap();
        assert_eq!(digest(&flat(&agg.landmarks)), c.get("aggregate").unwrap().as_str().unwrap(), "aggregate, seed {seed}");
        assert_eq!(agg.frontal_index as f64, c.get("frontalIndex").unwrap().as_f64().unwrap());
        assert_eq!(bits(agg.mean_frontality), c.get("meanFrontality").unwrap().as_str().unwrap());
        if let Some(want) = c.get("fprint").and_then(Value::as_str) {
            let (fp, _, _) = fclone::fclone_frames(&fr, 5).unwrap();
            assert_eq!(fp.hash, want, "fclone(frames) faceprint, seed {seed}");
            printed += 1;
        } else if n < 5 {
            assert!(fclone::fclone_frames(&fr, 5).is_err());
        }
    }
    assert_eq!((cases.len(), printed), (60, 30));
}
