// SPDX-License-Identifier: MIT OR Apache-2.0
//
// layout_probe — prints the byte offsets of the whisper.cpp internals the oracle reads.
//
// whisper.cpp's public API has no getter for the log-mel spectrogram it computes (`whisper_state::mel`), for the
// model's tensor map (`whisper_context::model.tensors`) or for the mel filterbank it loaded. Those are the very
// values voaice.rs must reproduce, so the oracle reads them out of the SHIPPED library's own objects. To know where
// they are, this probe includes the pinned source (the struct definitions live only in src/whisper.cpp) and asks the
// same compiler, with the same flags, for offsetof(). It is a build-time tool: its own copy of the code is never
// called. The oracle then self-checks each offset against a public getter (n_len, n_mel, tensor count) and refuses
// to run if any disagrees, so a layout mismatch can never pass silently.
#include "whisper.cpp"   // the pinned upstream source (include path: upstream/whisper.cpp/src)
#include <cstddef>
#include <cstdio>

#pragma GCC diagnostic ignored "-Winvalid-offsetof"

int main() {
    std::printf("// generated by testing/oracle/layout_probe.cpp against the pinned whisper.cpp — do not edit\n");
    std::printf("#define VOAICE_OFF_STATE_MEL      %zu\n", offsetof(whisper_state, mel));
    std::printf("#define VOAICE_OFF_STATE_EMBD_ENC %zu\n", offsetof(whisper_state, embd_enc));
    std::printf("#define VOAICE_OFF_CTX_MODEL      %zu\n", offsetof(whisper_context, model));
    std::printf("#define VOAICE_OFF_MODEL_FILTERS  %zu\n", offsetof(whisper_model, filters));
    std::printf("#define VOAICE_OFF_MODEL_TENSORS  %zu\n", offsetof(whisper_model, tensors));
    std::printf("#define VOAICE_OFF_MODEL_N_LOADED %zu\n", offsetof(whisper_model, n_loaded));
    // (0.0.6) the schedulers, so the oracle can observe each node through ggml's eval callback, and embd_conv
    std::printf("#define VOAICE_OFF_STATE_SCHED_CONV   %zu\n", offsetof(whisper_state, sched_conv));
    std::printf("#define VOAICE_OFF_STATE_SCHED_ENCODE %zu\n", offsetof(whisper_state, sched_encode));
    std::printf("#define VOAICE_OFF_STATE_EMBD_CONV    %zu\n", offsetof(whisper_state, embd_conv));
    std::printf("#define VOAICE_OFF_WSCHED_SCHED       %zu\n", offsetof(whisper_sched, sched));
    // (0.1.1) the cross graph's scheduler and the cross-attention KV cache it writes
    std::printf("#define VOAICE_OFF_STATE_SCHED_CROSS  %zu\n", offsetof(whisper_state, sched_cross));
    std::printf("#define VOAICE_OFF_STATE_KV_CROSS     %zu\n", offsetof(whisper_state, kv_cross));
    std::printf("#define VOAICE_OFF_KV_K               %zu\n", offsetof(whisper_kv_cache, k));
    std::printf("#define VOAICE_OFF_KV_V               %zu\n", offsetof(whisper_kv_cache, v));
    // (0.1.2) the decoder's scheduler and the batch whisper_decode_internal reads its inputs from
    std::printf("#define VOAICE_OFF_STATE_SCHED_DECODE %zu\n", offsetof(whisper_state, sched_decode));
    std::printf("#define VOAICE_OFF_STATE_BATCH        %zu\n", offsetof(whisper_state, batch));
    std::printf("#define VOAICE_SIZEOF_BATCH       %zu\n", sizeof(whisper_batch));
    std::printf("#define VOAICE_SIZEOF_MEL         %zu\n", sizeof(whisper_mel));
    std::printf("#define VOAICE_SIZEOF_FILTERS     %zu\n", sizeof(whisper_filters));
    return 0;
}
